### ISSUE TITLE
Cross Origin Resource Sharing?

### ISSUE THREAD

**Issue by makachung0** [krampstudio/aja.js#34]
I would like to ask if aja.js supports some parameters like CrossDomain:true in order to enable the CORS features, thanks

**Comment by krampstudio** [comment]
Good question! 
It will work as is, just set the correct URL and ensure you're web server adds the correct headers.
However, aja.js doesn't support (yet), the `withCredentials` parameter. So if you don't need to share the credentials, you can use aja.js. 

Otherwise, let me know and I'll address the issues
